# permissions for end users to edit finbackupconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: finbackupconfig-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: fin
    app.kubernetes.io/part-of: fin
    app.kubernetes.io/managed-by: kustomize
  name: finbackupconfig-editor-role
rules:
- apiGroups:
  - fin.cybozu.io
  resources:
  - finbackupconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - fin.cybozu.io
  resources:
  - finbackupconfigs/status
  verbs:
  - get
