name: "Main"
on:
  pull_request:
    paths-ignore:
      - "**/*.md"
  push:
    paths-ignore:
      - "**/*.md"
    branches:
      - "main"
jobs:
  build:
    name: "build"
    runs-on: "ubuntu-22.04"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: "go.mod"
      - run: make build
      - run: make lint
      - run: make test
